/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cledatabase;

import java.awt.Frame;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RemixTheIdiot
 */
public class FrameCredEnrollWiz extends javax.swing.JFrame {
    
    Frame parentframe;
    
    DefaultTableModel studvalid = new DefaultTableModel();
    JTable studstable = new JTable(studvalid);
    DefaultTableModel credvalid = new DefaultTableModel();
    JTable credtable = new JTable(credvalid);
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameCredEnrollWiz.class.getName());

    /**
     * Creates new form FrameCredEnrollWiz
     */
    public FrameCredEnrollWiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelWizName = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        textStudentNumber = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        textStudentName = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        comboStudentStatus = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        dateStudentEnroll = new com.toedter.calendar.JDateChooser();
        buttonAddStudent = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        dateStudentComp = new com.toedter.calendar.JDateChooser();
        spinnerScore = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        buttonAddStudent1 = new javax.swing.JButton();
        buttonClearDate = new javax.swing.JButton();
        buttonClearDate1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        labelWizName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelWizName.setText("[Enroll Wizard]");

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setText("Student Number: ");

        textStudentNumber.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textStudentNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textStudentNumberActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel29.setText("Student Name:");

        textStudentName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel32.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel32.setText("Status:");

        comboStudentStatus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboStudentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Failed", "Complete", "Incomplete" }));

        jLabel33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel33.setText("Enrollment Date:");

        dateStudentEnroll.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        buttonAddStudent.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        buttonAddStudent.setText("Add Student");
        buttonAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddStudentActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel34.setText("Completion Date:");

        dateStudentComp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        spinnerScore.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        spinnerScore.setModel(new javax.swing.SpinnerNumberModel());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Score:");

        buttonAddStudent1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        buttonAddStudent1.setText("Update Student");
        buttonAddStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddStudent1ActionPerformed(evt);
            }
        });

        buttonClearDate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonClearDate.setText("Clear");
        buttonClearDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearDateActionPerformed(evt);
            }
        });

        buttonClearDate1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonClearDate1.setText("Clear");
        buttonClearDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearDate1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textStudentName)
                            .addComponent(textStudentNumber)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(comboStudentStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonClearDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateStudentEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(spinnerScore)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonClearDate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateStudentComp, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelWizName)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonAddStudent1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelWizName)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textStudentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboStudentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateStudentEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateStudentComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel34)
                                .addComponent(buttonClearDate)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonAddStudent)
                            .addComponent(buttonAddStudent1))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonClearDate1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddStudentActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) credtable.getModel();
        String date = "N/A";
        String enddate = "N/A";
        if (dateStudentEnroll.getDate() != null) {
            int day = dateStudentEnroll.getCalendar().get(Calendar.DATE);
            int year = dateStudentEnroll.getCalendar().get(Calendar.YEAR);
            int monthnum = dateStudentEnroll.getCalendar().get(Calendar.MONTH);
            String month = "";
            switch (monthnum) {
                case 0 -> month = "January";
                case 1 -> month = "February";
                case 2 -> month = "March";
                case 3 -> month = "April";
                case 4 -> month = "May";
                case 5 -> month = "June";
                case 6 -> month = "July";
                case 7 -> month = "August";
                case 8 -> month = "September";
                case 9 -> month = "October";
                case 10 -> month = "November";
                case 11 -> month = "December";
            }
            date = month + " " + day + ", " + year;
        }
        if (dateStudentComp.getDate() != null) {
            int endday = dateStudentComp.getCalendar().get(Calendar.DATE);
            int endyear = dateStudentComp.getCalendar().get(Calendar.YEAR);
            int endmonthnum = dateStudentComp.getCalendar().get(Calendar.MONTH);
            String endmonth = "";
            switch (endmonthnum) {
                case 0 -> endmonth = "January";
                case 1 -> endmonth = "February";
                case 2 -> endmonth = "March";
                case 3 -> endmonth = "April";
                case 4 -> endmonth = "May";
                case 5 -> endmonth = "June";
                case 6 -> endmonth = "July";
                case 7 -> endmonth = "August";
                case 8 -> endmonth = "September";
                case 9 -> endmonth = "October";
                case 10 -> endmonth = "November";
                case 11 -> endmonth = "December";
            }
            enddate = endmonth + " " + endday + ", " + endyear;
        }
        model.addRow(new Object[]{ textStudentNumber.getText(), textStudentName.getText(), comboStudentStatus.getSelectedItem(), date, enddate, spinnerScore.getValue() });
    }//GEN-LAST:event_buttonAddStudentActionPerformed

    private void textStudentNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textStudentNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textStudentNumberActionPerformed

    private void buttonAddStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddStudent1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) credtable.getModel();
        int select = credtable.getSelectedRow();
        String date = "N/A";
        String enddate = "N/A";
        if (dateStudentEnroll.getDate() != null) {
            int day = dateStudentEnroll.getCalendar().get(Calendar.DATE);
            int year = dateStudentEnroll.getCalendar().get(Calendar.YEAR);
            int monthnum = dateStudentEnroll.getCalendar().get(Calendar.MONTH);
            String month = "";
            switch (monthnum) {
                case 0 -> month = "January";
                case 1 -> month = "February";
                case 2 -> month = "March";
                case 3 -> month = "April";
                case 4 -> month = "May";
                case 5 -> month = "June";
                case 6 -> month = "July";
                case 7 -> month = "August";
                case 8 -> month = "September";
                case 9 -> month = "October";
                case 10 -> month = "November";
                case 11 -> month = "December";
            }
            date = month + " " + day + ", " + year;
        }
        if (dateStudentComp.getDate() != null) {
            int endday = dateStudentComp.getCalendar().get(Calendar.DATE);
            int endyear = dateStudentComp.getCalendar().get(Calendar.YEAR);
            int endmonthnum = dateStudentComp.getCalendar().get(Calendar.MONTH);
            String endmonth = "";
            switch (endmonthnum) {
                case 0 -> endmonth = "January";
                case 1 -> endmonth = "February";
                case 2 -> endmonth = "March";
                case 3 -> endmonth = "April";
                case 4 -> endmonth = "May";
                case 5 -> endmonth = "June";
                case 6 -> endmonth = "July";
                case 7 -> endmonth = "August";
                case 8 -> endmonth = "September";
                case 9 -> endmonth = "October";
                case 10 -> endmonth = "November";
                case 11 -> endmonth = "December";
            }
            enddate = endmonth + " " + endday + ", " + endyear;
        }
        System.out.println(select);
        model.setValueAt(textStudentNumber.getText(), select, 0);
        model.setValueAt(textStudentName.getText(), select, 1);
        model.setValueAt(comboStudentStatus.getSelectedItem(), select, 2);
        model.setValueAt(date, select, 3);
        model.setValueAt(enddate, select, 4);
        model.setValueAt(spinnerScore.getValue(), select, 5);
    }//GEN-LAST:event_buttonAddStudent1ActionPerformed

    private void buttonClearDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearDateActionPerformed
        // TODO add your handling code here:
        dateStudentComp.setDate(null);
    }//GEN-LAST:event_buttonClearDateActionPerformed

    private void buttonClearDate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearDate1ActionPerformed
        // TODO add your handling code here:
        dateStudentComp.setDate(null);
    }//GEN-LAST:event_buttonClearDate1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameCredEnrollWiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddStudent;
    private javax.swing.JButton buttonAddStudent1;
    private javax.swing.JButton buttonClearDate;
    private javax.swing.JButton buttonClearDate1;
    private javax.swing.JComboBox<String> comboStudentStatus;
    private com.toedter.calendar.JDateChooser dateStudentComp;
    private com.toedter.calendar.JDateChooser dateStudentEnroll;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    public javax.swing.JLabel labelWizName;
    private javax.swing.JSpinner spinnerScore;
    private javax.swing.JTextField textStudentName;
    private javax.swing.JTextField textStudentNumber;
    // End of variables declaration//GEN-END:variables
}
