/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cledatabase;

import java.awt.Container;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RemixTheIdiot
 */
public class PanelCred extends javax.swing.JPanel {
    
    DefaultTableModel validList = new DefaultTableModel();
    JTable enrollMcValid = new JTable(validList);
    
    DefaultTableModel mainstuds = new DefaultTableModel();
    JTable mainstudstab = new JTable(mainstuds);
    
    public static void sortbyColumn(String a[][], int c){      
      Arrays.sort(a, (x, y) -> x[c].compareTo(y[c]));
    }
    
    public static void sortbyNumber(int a[][], int c){      
      Arrays.sort(a, (x, y) -> Integer.compare(x[c],y[c])); 
    }
    
    // SORT BY DATE METHOD - 2d array method to sort an array of dates
    
    public static void sortbyDate(Date a[][], int c){      
      Arrays.sort(a, (x, y) -> x[c].compareTo(y[c]));
    }
    
    /*public void getStudentList() {
        DefaultTableModel model = (DefaultTableModel) enrollMcValid.getModel();
        DefaultTableModel table = (DefaultTableModel) tableCredEnrolls.getModel();
        table.setRowCount(0);
        
        int count = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            if (String.valueOf(model.getValueAt(i, 2)).equals(textAreaName.getText())) {
                table.addRow(new Object[] { model.getValueAt(i, 0), model.getValueAt(i, 1) });
                count += 1;
            }
        }
        labelEnrollCount.setText(String.valueOf(count));
    }*/

    /**
     * Creates new form PanelCred
     */
    public PanelCred() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaName = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDesc = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        spinnerDuration = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaPrereq = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        labelEnrollCount = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelCompleteCount = new javax.swing.JLabel();
        buttonNewStudent = new javax.swing.JButton();
        buttonFilter = new javax.swing.JButton();
        textFieldFilter = new javax.swing.JTextField();
        buttonDel = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        textAreaCode = new javax.swing.JTextArea();
        comboFilter = new javax.swing.JComboBox<>();
        buttonEnrollValidate = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableCredEnrolls = new javax.swing.JTable();
        buttonSort = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        textAreaDept = new javax.swing.JTextArea();
        buttonNewStudent1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        textAreaName.setColumns(20);
        textAreaName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textAreaName.setLineWrap(true);
        textAreaName.setRows(2);
        textAreaName.setText("Credential Name");
        textAreaName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                textAreaNamePropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(textAreaName);

        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        textAreaDesc.setColumns(20);
        textAreaDesc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textAreaDesc.setRows(2);
        textAreaDesc.setText("desc");
        jScrollPane1.setViewportView(textAreaDesc);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Duration (hrs):");

        spinnerDuration.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        spinnerDuration.setModel(new javax.swing.SpinnerNumberModel());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Prerequisites:");

        textAreaPrereq.setColumns(20);
        textAreaPrereq.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textAreaPrereq.setRows(2);
        textAreaPrereq.setText("prereq");
        jScrollPane3.setViewportView(textAreaPrereq);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel4.setText("Enrolled: ");

        labelEnrollCount.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        labelEnrollCount.setText("0");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel6.setText("Commpletion Rate: ");

        labelCompleteCount.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        labelCompleteCount.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelCompleteCount.setText("0%");

        buttonNewStudent.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonNewStudent.setText("Enroll Wizard");
        buttonNewStudent.setToolTipText("Opens a Wizard for Student Enrollment of this Credential.");
        buttonNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewStudentActionPerformed(evt);
            }
        });

        buttonFilter.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonFilter.setText("Search Students");
        buttonFilter.setToolTipText("List must be Validated before performing. Click this to use the View All option.");
        buttonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFilterActionPerformed(evt);
            }
        });

        textFieldFilter.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textFieldFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldFilterActionPerformed(evt);
            }
        });

        buttonDel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonDel.setText("Remove Program");
        buttonDel.setToolTipText("Removes this credential from view only. Must validate to confirm removal.");
        buttonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDelActionPerformed(evt);
            }
        });

        jScrollPane5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        textAreaCode.setColumns(20);
        textAreaCode.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textAreaCode.setLineWrap(true);
        textAreaCode.setRows(1);
        textAreaCode.setText("Credential Code");
        jScrollPane5.setViewportView(textAreaCode);

        comboFilter.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        comboFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student No.", "Name", "Status", "Enroll Date", "Completion Date", "Score", "View All" }));
        comboFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFilterActionPerformed(evt);
            }
        });

        buttonEnrollValidate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonEnrollValidate.setText("Validate Enrolled");
        buttonEnrollValidate.setToolTipText("Validation used only for Sort and Search Functionality.");
        buttonEnrollValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnrollValidateActionPerformed(evt);
            }
        });

        tableCredEnrolls.setAutoCreateRowSorter(true);
        tableCredEnrolls.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableCredEnrolls.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student No.", "Student Name", "Status", "Enrollment Date", "Completion Date", "Score"
            }
        ));
        tableCredEnrolls.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane4.setViewportView(tableCredEnrolls);
        if (tableCredEnrolls.getColumnModel().getColumnCount() > 0) {
            tableCredEnrolls.getColumnModel().getColumn(0).setResizable(false);
            tableCredEnrolls.getColumnModel().getColumn(0).setPreferredWidth(100);
            tableCredEnrolls.getColumnModel().getColumn(1).setResizable(false);
            tableCredEnrolls.getColumnModel().getColumn(1).setPreferredWidth(200);
            tableCredEnrolls.getColumnModel().getColumn(2).setResizable(false);
            tableCredEnrolls.getColumnModel().getColumn(2).setPreferredWidth(100);
            tableCredEnrolls.getColumnModel().getColumn(3).setResizable(false);
            tableCredEnrolls.getColumnModel().getColumn(3).setPreferredWidth(150);
            tableCredEnrolls.getColumnModel().getColumn(4).setResizable(false);
            tableCredEnrolls.getColumnModel().getColumn(4).setPreferredWidth(150);
            tableCredEnrolls.getColumnModel().getColumn(5).setResizable(false);
            tableCredEnrolls.getColumnModel().getColumn(5).setPreferredWidth(50);
        }

        buttonSort.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonSort.setText("Sort Students");
        buttonSort.setToolTipText("List must be Validated before performing.");
        buttonSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSortActionPerformed(evt);
            }
        });

        jScrollPane6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        textAreaDept.setColumns(20);
        textAreaDept.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textAreaDept.setLineWrap(true);
        textAreaDept.setRows(1);
        textAreaDept.setText("Department");
        jScrollPane6.setViewportView(textAreaDept);

        buttonNewStudent1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonNewStudent1.setText("Remove Row(s)");
        buttonNewStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewStudent1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerDuration))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelEnrollCount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCompleteCount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonNewStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonNewStudent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboFilter, 0, 102, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonEnrollValidate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelEnrollCount)
                    .addComponent(jLabel6)
                    .addComponent(labelCompleteCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNewStudent)
                    .addComponent(buttonEnrollValidate)
                    .addComponent(buttonNewStudent1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDel)
                    .addComponent(buttonSort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFilter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDelActionPerformed
        // TODO add your handling code here:
        Container that = this.getParent();
        
        that.remove(this);
        that.revalidate();
        that.repaint();
    }//GEN-LAST:event_buttonDelActionPerformed

    private void textAreaNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_textAreaNamePropertyChange
        // TODO add your handling code here:
        //MainFrame.credValid.
    }//GEN-LAST:event_textAreaNamePropertyChange

    private void buttonNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewStudentActionPerformed
        // TODO add your handling code here:
        Container that = this.getParent();
        FrameCredEnrollWiz enrollwiz = new FrameCredEnrollWiz();
        enrollwiz.credtable = tableCredEnrolls;
        enrollwiz.studstable = mainstudstab;
        enrollwiz.labelWizName.setText("[" + textAreaName.getText() + " - Enroll Wizard]");
        enrollwiz.setVisible(true);
    }//GEN-LAST:event_buttonNewStudentActionPerformed

    private void buttonEnrollValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnrollValidateActionPerformed
        // TODO add your handling code here:
        int confirmvalid = JOptionPane.showConfirmDialog(null, "This will overwrite current validated list with the current one. Are you sure?","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (confirmvalid == JOptionPane.YES_OPTION) {
            DefaultTableModel model = (DefaultTableModel) tableCredEnrolls.getModel();
            DefaultTableModel valid = (DefaultTableModel) enrollMcValid.getModel();

            valid.setRowCount(model.getRowCount());
            valid.setColumnCount(model.getColumnCount());
            
            labelEnrollCount.setText(String.valueOf(tableCredEnrolls.getRowCount()));
            
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    valid.setValueAt(model.getValueAt(i, j), i, j);
                }
            }
            
            model.setRowCount(0);
            for (int i = 0; i < valid.getRowCount(); i++) {
                    model.addRow(new Object[]{valid.getValueAt(i, 0), valid.getValueAt(i, 1), valid.getValueAt(i, 2), valid.getValueAt(i, 3), valid.getValueAt(i, 4), valid.getValueAt(i, 5)});
            }
            
            double total = Double.parseDouble(labelEnrollCount.getText());
            double complete = 0;
            
            for (int i = 0; i < model.getRowCount(); i++) {
                if (String.valueOf(model.getValueAt(i, 2)).equalsIgnoreCase("complete")) {
                    complete += 1;
                }
            }
            
            double fin = (complete/total)*100;
            
            labelCompleteCount.setText(String.format("%.0f", fin) + "%");
        }
    }//GEN-LAST:event_buttonEnrollValidateActionPerformed

    private void buttonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFilterActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tableCredEnrolls.getModel();
        DefaultTableModel valid = (DefaultTableModel) enrollMcValid.getModel();

        model.setRowCount(0);

        int action = comboFilter.getSelectedIndex();
        
        if (action == 6) {
            model.setRowCount(valid.getRowCount());

            for (int i = 0; i < valid.getRowCount(); i++) {
                for (int j = 0; j < valid.getColumnCount(); j++) {
                    model.setValueAt(valid.getValueAt(i, j), i, j);
                }
            }
        } else {
            String filter = textFieldFilter.getText();
            for (int i = 0; i < valid.getRowCount(); i++) {
                String search = String.valueOf(valid.getValueAt(i, action));
                if (search.toLowerCase().contains(filter.toLowerCase())) {
                    model.addRow(new Object[]{valid.getValueAt(i, 0), valid.getValueAt(i, 1), valid.getValueAt(i, 2), valid.getValueAt(i, 3), valid.getValueAt(i, 4), valid.getValueAt(i, 5)});
                }
            }
        }
    }//GEN-LAST:event_buttonFilterActionPerformed

    private void buttonSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSortActionPerformed
        // TODO add your handling code here:
        DefaultTableModel sortstudent = (DefaultTableModel) tableCredEnrolls.getModel();
        DefaultTableModel confirm = (DefaultTableModel) enrollMcValid.getModel();
        
        if (comboFilter.getSelectedIndex() != 6) {
            String sortarray[][] = new String[sortstudent.getRowCount()][sortstudent.getColumnCount()];
            int sortint[][] = new int[sortstudent.getRowCount()][2];
            Date sortdate[][] = new Date[sortstudent.getRowCount()][2];
            
            for (int i = 0; i < sortarray.length; i++) {
                for (int j = 0; j < sortarray[i].length; j++) {
                    if (sortstudent.getValueAt(i, j) != null) {
                        sortarray[i][j] = String.valueOf(sortstudent.getValueAt(i, j));
                    } else {
                        sortarray[i][j] = "";
                    }
                }
            }
            
            if (comboFilter.getSelectedIndex() == 3 || comboFilter.getSelectedIndex() == 4) {
                SimpleDateFormat sdf = new SimpleDateFormat("MMM d, yyyy");
                for (int i = 0; i < sortarray.length; i++) {
                    try {
                        sortdate[i][0] = sdf.parse(sortarray[i][comboFilter.getSelectedIndex()]);
                        System.out.println(sortdate[i][0]);
                    } catch (ParseException ex) {
                        System.getLogger(MainFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                    }
                }
                sortbyDate(sortdate, 0);
                confirm.setRowCount(0);
                int process = 0;
                while (process < sortdate.length) {
                    for (int i = 0; i < sortdate.length; i++) {
                        try {
                            Date getDate = sdf.parse(sortarray[i][comboFilter.getSelectedIndex()]);
                            if (sortdate[process][0].compareTo(getDate) == 0 && sortdate[i][1] == null) {
                                confirm.addRow(new Object[] { sortarray[i][0], sortarray[i][1], sortarray[i][2], sortarray[i][3], sortarray[i][4], sortarray[i][5] });
                                sortdate[i][1] = getDate;
                                process += 1;
                                break;
                            }
                        } catch (ParseException ex) {
                            System.getLogger(MainFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                        }
                    }
                }
            } else if (comboFilter.getSelectedIndex() == 5) {
                for (int i = 0; i < sortarray.length; i++) {
                    sortint[i][0] = Integer.parseInt(sortarray[i][5]);
                    sortint[i][1] = 0;
                }
                sortbyNumber(sortint, 0);
                confirm.setRowCount(0);
                int process = 0;
                while (process < sortint.length) {
                    for (int i = 0; i < sortint.length; i++) {
                        if (sortint[process][0] == Integer.parseInt(sortarray[i][5]) && sortint[i][1] == 0) {
                            confirm.addRow(new Object[] { sortarray[i][0], sortarray[i][1], sortarray[i][2], sortarray[i][3], sortarray[i][4], sortarray[i][5] });
                            sortint[i][1] = 1;
                            process += 1;
                            break;
                        }
                    }
                }
            } else {
                sortbyColumn(sortarray, comboFilter.getSelectedIndex());

                for (int i = 0; i < sortarray.length; i++) {
                    for (int j = 0; j < sortarray[i].length; j++) {
                        // sortstudent.setValueAt(sortarray[i][j], i, j);
                        confirm.setValueAt(sortarray[i][j], i, j);
                    }
                }
            }
            sortstudent.setRowCount(0);
            for (int i = 0; i < confirm.getRowCount(); i++) {
                    sortstudent.addRow(new Object[]{confirm.getValueAt(i, 0), confirm.getValueAt(i, 1), confirm.getValueAt(i, 2), confirm.getValueAt(i, 3), confirm.getValueAt(i, 4), confirm.getValueAt(i, 5)});
            }
        }
    }//GEN-LAST:event_buttonSortActionPerformed

    private void textFieldFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldFilterActionPerformed

    private void buttonNewStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewStudent1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tableCredEnrolls.getModel();
        for (int i = 0; i < tableCredEnrolls.getSelectedRowCount(); i++) {
            model.removeRow(tableCredEnrolls.getSelectedRow() + i);
        }
        model.removeRow(tableCredEnrolls.getSelectedRow());
    }//GEN-LAST:event_buttonNewStudent1ActionPerformed

    private void comboFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFilterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buttonDel;
    private javax.swing.JButton buttonEnrollValidate;
    private javax.swing.JButton buttonFilter;
    private javax.swing.JButton buttonNewStudent;
    private javax.swing.JButton buttonNewStudent1;
    private javax.swing.JButton buttonSort;
    private javax.swing.JComboBox<String> comboFilter;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JLabel labelCompleteCount;
    public javax.swing.JLabel labelEnrollCount;
    public javax.swing.JSpinner spinnerDuration;
    public javax.swing.JTable tableCredEnrolls;
    public javax.swing.JTextArea textAreaCode;
    public javax.swing.JTextArea textAreaDept;
    public javax.swing.JTextArea textAreaDesc;
    public javax.swing.JTextArea textAreaName;
    public javax.swing.JTextArea textAreaPrereq;
    private javax.swing.JTextField textFieldFilter;
    // End of variables declaration//GEN-END:variables
}
